/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package glasscat.as1.app;
import glasscat.as1.dao.impl.UserDao;
import glasscat.as1.entity.UserEntity;
import glasscat.as1.util.IDUtil;
import glasscat.as1.util.StringUtil;
import java.util.List;
import javax.ejb.EJB;
import javax.swing.JOptionPane;

/**
 *
 * @author Sun Yeqing
 */
public class Register extends javax.swing.JFrame {
    private static UserDao userDao;
    private javax.swing.JFrame login;
    /**
     * Creates new form Register
     */
    public Register(UserDao _userDao, javax.swing.JFrame loginFrame) {
        login = loginFrame;
        userDao = _userDao;
        initComponents();
        this.setSize(445, 562);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Password:");

        jLabel5.setText("Repeat:");

        jButton1.setText("Commit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Return");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setText("E-mail:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String email = jTextField1.getText();
        String pswd = jTextField4.getText();
        String repeat = jTextField5.getText();
        UserEntity userEntity = new UserEntity();
        // check email
        if (!StringUtil.isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, "Invalid e-mail!", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // check password valid
        if (!StringUtil.isValidPassword(pswd)) {
            JOptionPane.showMessageDialog(this, "Invalid password!\nIt should contain digits, both upper and lower letters and special characters, 8 to 20 characters long.", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //check password confirm
        if (!repeat.equals(pswd)) {
            JOptionPane.showMessageDialog(this, "Entered passwords differ!", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // client check finished
        
        // database check
        List<UserEntity> users = userDao.findByEmail(email);
        if (users != null && !users.isEmpty()) {
            // users not null and contains at least one user
            JOptionPane.showMessageDialog(this, "User exits!", "Info", JOptionPane.ERROR_MESSAGE);
            return;
        }        
        // database check finished
        
        // new user and insert
        UserEntity user = new UserEntity();
        user.setEmail(email);
        user.setPassword(pswd);
        user.setId(IDUtil.getUUID());
        user.setMembershipLevel(0);
        userDao.save(user);
        
        // back to Login jframe
        this.setVisible(false);
        this.login.setVisible(true);
        
        // 来自男票的注释：不要这么多层if嵌套，能拆的逻辑就拆出去，放过自己也放过别人啊_(:з」∠)_
//        if (StringUtil.isValidEmail(email)) {
//            if (StringUtil.isValidPassword(pswd)) {
//                if (repeat.equals(pswd)) {
//                    List<UserEntity> userEntities = userDao.findByEmail(email);
//                    if (userEntities == null && userEntities.size() == 0) {
//                        userEntity.setEmail(email);
//                        userEntity.setPassword(pswd);
//                        userEntity.setId(IDUtil.getUUID());
//                        userDao.save(userEntity);
//                        this.setVisible(false);
//                        new Login().setVisible(true);
//                    } else {
//                        JOptionPane.showMessageDialog(this, "User exits!", "Info", JOptionPane.ERROR_MESSAGE);
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(this, "Entered passwords differ!", "Info", JOptionPane.ERROR_MESSAGE);
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Invalid password!\nIt should contain digits, both upper and lower letters and special characters, 8 to 20 characters long.", "Info", JOptionPane.ERROR_MESSAGE);
//            }
//        } else {
//            JOptionPane.showMessageDialog(this, "Invalid e-mail!", "Info", JOptionPane.ERROR_MESSAGE);
//        }
         
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
